/*
 *
 *
 */
$(function() { 
	var insptrgrid = $('#insptracktbl');
	insptrgrid.jqGrid({    //17 cols
		datatype: "json",
   		//url:"/Myelclass/SampleInsertAction.do", 
    	colNames:['ID','Status','CtNo','InspDate','QCtlr','ArticleID','Article','Color','InspCdn','testID','GradeId','RejID','TotInspctd','comments'],  
    	colModel :[ 
					{name: 'inspid', index: 'inspid', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'status', index: 'status', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'contractno', index: 'contractno', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'inspdate', index: 'inspdate', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'qualitycontroller', index: 'qualitycontroller', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'articleid', index: 'articleid', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'article', index: 'article', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'color', index: 'color', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'inspcdn', index: 'inspcdn', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'testid', index: 'testid', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'gradeid', index: 'gradeid', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'rejectsid', index: 'rejectsid', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'totinspected', index: 'totinspected', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'inspcomments', index: 'inspcomments', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					/*{name: 'testtype', index: 'testtype', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'pcstested', index: 'pcstested', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'result', index: 'result', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'comments', index: 'comments', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'grade', index: 'grade', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'skincount', index: 'skincount', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'grtotinspected', index: 'grtotinspected', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'percent', index: 'percent', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'comment', index: 'comment', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'arttype', index: 'arttype', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'rjtotinspected', index: 'rjtotinspected', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'totpassed', index: 'totpassed', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'totrejects', index: 'totrejects', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'subsrejects', index: 'subsrejects', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'sizerejects', index: 'sizerejects', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'selecrejects', index: 'selecrejects', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'colorrejects', index: 'colorrejects', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'orgrejects', index: 'orgrejects', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},
					{name: 'otherrejects', index: 'otherrejects', align:'center', width:60, editable:true, sortable: true, hidden:false, 
					},*/
    	],
    	jsonReader : {  
    		repeatitems:false,
    		root: "rows",
    		page: "page", //calls first
    		total: "total" ,//calls Second
    		records: "records" //calls Third
    	},  
    	caption: "Inspection Tracking Report",
    	pager: '#insptrackpager',
    	rowNum:10, 
    	rowList:[20,30,40],
    	loadtext: "Bow Bow",
    	height : "auto",
    	width:"auto",  
    	sortname: 'contractNumber',  
    	sortorder: 'desc',
    	scroll: 1, //Check here
    	editurl: '',
    	emptyrecords: 'No records to display',
    	}).jqGrid("navGrid",'#insptrackpager',{
    		edit: true, add: true, del: true, 
			search: false, refresh: true, view: true
    	});
});